### ISSUE TITLE
Menu drawer button is not displayed on iPhone 5C

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetifyjs.com#111]
Tested on Chrome and Safari

**Comment by nekosaur** [comment]
Please provide an image of how it looks.

**Comment by peluprvi** [comment]
@nekosaur sorry but my iPhone 5C has gone. I can't test on it anymore.
The jumbotron area was too high and the "Get Started" button was below the fold.
But now the jumbotron area has a smaller height and I think it may fit (tested on desktop Chrome inspector).
