### ISSUE TITLE
Create an upgrade guide page

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetifyjs.com#112]
A list or a table with all migration/upgrade links, pointing to github release patch notes page:

Example:

from | to  | upgrade guide
---- |----|----
0.17.0 | 1.0.0 | Comimg soon
0.16.0 | 0.17.0 | <https://github.com/vuetifyjs/vuetify/releases/tag/v0.17.0>
0.15.0 | 0.16.0 | <https://github.com/vuetifyjs/vuetify/releases/tag/v0.16.0>

**Comment by johnleider** [comment]
This can/should be done as a .md file on the main repo

**Comment by kelp404** [comment]
https://github.com/vuetifyjs/vuetify/releases/tag/v1.0.0
