### ISSUE TITLE
Request: Disable pagination on API tables.

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetifyjs.com#122]
An API table is not what I would expect to have pagination on. I personally would like to see all options for whatever component I am using.

**Comment by zaken** [comment]
Not disabling pagination for now, but we're working on a solution to save your items per page preferences in browser's local storage.

**Comment by Maxhodges** [comment]
> but we're working on a solution to save your items per page 

Do you choose to fix a bad design by making it move complicated? Please just show all props. That's the right thing to do. It's simple, requires less complexity, allows people to search for props with CTRL+F in the browser. 

Also I think you should move API to the top, and get rid of the "Usage" section by merging it with the other Examples.

I recommend taking inspiration from React-Semantic-UI docs. They've done a good job, especially by showing all the props up top and includes links to example sections in the sidebar TOC

https://react.semantic-ui.com/elements/button

**Comment by Maxhodges** [comment]
this is clearly a recurring issue
![image](https://user-images.githubusercontent.com/957271/34512815-0587f758-f0a8-11e7-880b-8f1101407964.png)

![image](https://user-images.githubusercontent.com/957271/34512835-238863dc-f0a8-11e7-886c-9c54c236ea89.png)

**Comment by MatthewAry** [comment]
@zaken I understand that there are plans to store the pagination preferences in the local storage of the browser. But I think that hiding the complete list of the API is doing more harm than good because it interferes with prospective developers capability discovery process.

On every single docs page that I visit, I ALWAYS set the pagination to show all and I have to do this every single time. Initially when I started looking at the next docs I thought that the capabilities on next were severely lacking compared to the old version. This is clearly causing confusing and frustration amongst developers.

I imagine that the Data Tables component will have to be modified in order to support the capabilities you are waiting for. So, in the meantime, just disable the pagination on the API docs. Or reopen this issue so you can get more user feedback on this issue. It seems a bit premature to close right now.

**Comment by KaelWD** [comment]
We had an idea to separate the api and examples pages using tabs, and having cards instead of a table so more detailed information can be displayed.

**Comment by MatthewAry** [comment]
Yeah. Using cards instead of a table sounds like a good idea. There are few component features that I imagine would be really hard to express completely using the current format such as the headers array prop for the Data Table component. But instead of tabs, maybe it should be expansion panels.

You could make the layout of a component doc page like this.
- Description and Basic Example (always open, not in an expansion panel)
- API (open by default)
- Examples (closed by default)

**Comment by zaken** [comment]
TBH, I also didn't like the pagination choice. I think someone on discord brought that up and John said it's staying, that's why I closed this. I liked the old docs order of sections.

**Comment by Maxhodges** [comment]
yeah all this talk of pages and expansion panels is terrible. Prevents CTRL+F in the browser from finding everything and creates unnecessary extra clicks--there's just no benefit to it. @johnleider 

The pages even with all the props, just aren't that long. Look at [Stripe API docs](https://stripe.com/docs/api#intro)--it's all just one page. Yet it works great. One page per component is not excessively long by any means.

Also don't create a separate section for Usage and Examples. Usage is just a kind of example, so merge those two things into one.

React-Semantic-UI has a lot of props for some components, but it's not big deal. 
https://react.semantic-ui.com/modules/dropdown

It's quite efficient to see them all on one page. Keep it simple. You have better things to do than to persist and retrieve user pagination state and field new user questions about "where is such-and-such prop" because they didn't notice the pagination.

**Comment by johnleider** [comment]
For beta.3 I have removed the table pagination and set everything to display by default. We will be evaluating a more permanent solution next sprint.

**Comment by Maxhodges** [comment]
@johnleider it's looking much better. Sorry I had a hard time working on the design due to lack of experience. I'd keep "usage" with the other examples. Better to keep them all together instead of having a big props table in between.
