### ISSUE TITLE
Grid offset example does not properly show expected offsets for given labels

### ISSUE THREAD

**Issue by Larkenx** [vuetifyjs/vuetifyjs.com#129]
Current implementation
![image](https://user-images.githubusercontent.com/12945799/34277038-25ed1702-e672-11e7-81b1-a6062faab093.png)

Expected : https://codepen.io/anon/pen/ypJKdy?&editors=100
![image](https://user-images.githubusercontent.com/12945799/34277060-40affea6-e672-11e7-93b0-df29b639302e.png)

**Comment by johnleider** [comment]
fixed with #130
