### ISSUE TITLE
bottom-navigation (next.vuetifyjs.com) - Event 'update:active' fails when changes are made (click $emit v-btn)

### ISSUE THREAD

**Issue by adriaroms** [vuetifyjs/vuetifyjs.com#139]
bottom-navigation (next.vuetifyjs.com) - Event `update:active` fails when changes are made (click `$emit` `v-btn`). 

Basically if you try to change (tested in Chrome version 63 in macOS and Android 7) the tab for example from the `iconsAndText` file, we click on `Favorites`, visually it does not change (change the value of `e1` by payload 
 of the event) and shows the following error on the console:
<img width="428" alt="screen shot 2017-12-29 at 17 26 07" src="https://user-images.githubusercontent.com/34319045/34441648-689b426c-ecbd-11e7-9822-239d73f59ac8.png">

**Comment by nekosaur** [comment]
I'm not sure I understand. All of the examples are working for me without any errors in console.

Please provide explicit reproduction steps.

**Comment by adriaroms** [comment]
No problem, step by step:
1.- Go to `https://next.vuetifyjs.com/components/bottom-navigation#usage`
<img width="840" alt="screen shot 2017-12-31 at 16 07 42" src="https://user-images.githubusercontent.com/34319045/34462473-29c7eb7e-ee45-11e7-9451-1aaf32832f67.png">

2.- Click on Bottom Navigation Tab `Favorites`
<img width="198" alt="screen shot 2017-12-31 at 16 07 51" src="https://user-images.githubusercontent.com/34319045/34462482-536173f6-ee45-11e7-9baf-a3146fb74df4.png">

3.- Note that `Active` if changed to `Favorites`, but visually still selected `Recent` (and the error is already displayed in the console).

- Google Chrome 63.0.3239.108:
<img width="1145" alt="screen shot 2017-12-31 at 16 08 10" src="https://user-images.githubusercontent.com/34319045/34462498-9c7b019c-ee45-11e7-88e7-87c8fc3ff003.png">

- Firefox Quantum 57.0.1:
<img width="643" alt="screen shot 2017-12-31 at 16 09 20" src="https://user-images.githubusercontent.com/34319045/34462539-460ad106-ee46-11e7-8d4c-7c924cc30876.png">

tested in `Google Chrome 63.0.3239.108` and `Firefox Quantum 57.0.1`, under `macOS High Sierra 10.13.2`, today (DECEMBER 31, 2017)
I hope to have explained.

**Comment by KaelWD** [comment]
That's a bug in vuetify, not the documentation. 

Alpha 1: https://codepen.io/anon/pen/goWqej?editors=1000
Alpha 2: https://codepen.io/anon/pen/BJRMrG?editors=1000

It may have been fixed on dev, I'll have to check.
