### ISSUE TITLE
Snackbar hides below the footer/content

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetifyjs.com#179]
https://next.vuetifyjs.com/components/snackbars

![snackbar](https://user-images.githubusercontent.com/15625235/34657716-b522c7c2-f45b-11e7-8a44-354eb54f83e6.gif)

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/34659280-f997894a-f48a-11e7-89fd-8c332b949c09.png)

**Comment by KaelWD** [comment]
Regressed in 0587295d
