### ISSUE TITLE
[Issue] Last Two Examples in Navigation Drawers Docs are broken

### ISSUE THREAD

**Issue by MatthewAry** [vuetifyjs/vuetifyjs.com#182]
<img width="1142" alt="screen shot 2018-01-08 at 11 58 13 am" src="https://user-images.githubusercontent.com/157217/34687191-3f982cf8-f46b-11e7-8eb4-edc5b95fb45f.png">

The height in the preview area needs to be larger. The drawers should be hidden when they are untoggled and not visible outside the preview area.

**Comment by johnleider** [comment]
This has been resolved.
