### ISSUE TITLE
Broken version dropdown

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetifyjs.com#195]
![image](https://user-images.githubusercontent.com/15625235/34807967-270c9eee-f6be-11e7-8ddf-5811c1586eaa.png)

clicking on the older version leads to invalid page
https://next.vuetifyjs.com/releases/0.17/#/components/lists

**Comment by KaelWD** [comment]
still a problem, the releases don't have a /public directory
