### ISSUE TITLE
bug in theme generator

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetifyjs.com#196]
- open https://next.vuetifyjs.com/theme-generator
- click a new color
- click "Export theme"
- click "Use names"

![image](https://user-images.githubusercontent.com/15625235/34809084-6f0d3cd8-f6c5-11e7-9518-55f2bca95bb9.png)

BTW - I'd move generator to the "Styles & themes" section in navigation

**Comment by KaelWD** [comment]
The keys in that dialog shouldn't be quoted either.
