### ISSUE TITLE
Document theme variations and $vuetify.options

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetifyjs.com#202]
vuetifyjs/vuetify#2872

**Comment by NickLarsenNZ** [comment]
What does `themeVariations` do? I didn't quite understand from the documentation and I don't notice any different by adding or removing it.

**Comment by KaelWD** [comment]
Sets which theme colours have darken/lighten variants. I should probably have it default to all tbh, it only really makes a difference with SSR.

**Comment by NickLarsenNZ** [comment]
Oh right - makes sense now, thanks for the super quick reply.
