### ISSUE TITLE
Broken link on the search box results, "Layout - Grid"

### ISSUE THREAD

**Issue by pinguinosod** [vuetifyjs/vuetifyjs.com#213]
If you input the word "grid" into the search box, you get prompted with this:

![imagen](https://user-images.githubusercontent.com/28690088/34966694-3e2864d8-fa3c-11e7-9ca6-47860e23df83.png)

The second link, "Layout - Grid" is broken and it leads you to a 404 error.

I think the correct url is: https://next.vuetifyjs.com/components/grid which is in `UI components > Grid & breakpoints` on the menu.

Edit: i forgot to mention that i am talking about the docs for v1.0 beta

**Comment by johnleider** [comment]
This will be resolved once we switch next to production. Currently doc-search by agolia only crawls vuetifyjs.com.
