### ISSUE TITLE
Add notice regarding import of a-la-carte components in SFC files

### ISSUE THREAD

**Issue by nekosaur** [vuetifyjs/vuetifyjs.com#217]
We should add a notice to a-la-carte docs regarding the scenario where you want to import a vuetify component directly in an SFC file (not using `Vue.use(Vuetify, {})`). See https://github.com/vuetifyjs/vuetify/issues/3035

**Comment by wuservices** [comment]
@nekosaur I got here trying things like this from the docs, then trying to destructure:
```
import * as VDivider from 'vuetify/es5/components/VDivider';
import * as VSubheader from 'vuetify/es5/components/VSubheader';
```

However, these components (and maybe others?) only have a default exports. Is this something that I'd want to file an issue to fix the docs for, or something the code should be updated for to be more consistent?
