### ISSUE TITLE
text-field page broken in IE11

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetifyjs.com#230]
https://next.vuetifyjs.com/components/text-fields#example-password

- appended icon doesn't toggle password visibility
- source code icon doesn't open the source code
- theme button doesn't switch the theme

UPDATE: other examples on this page are broken too (label doesn't animate when field is focused in the first example, theme and source code buttons doesn't work anywhere, maybe something more)

**Comment by KaelWD** [comment]
That got rid of the console errors, but the page still doesn't work for some reason.

**Comment by KaelWD** [comment]
IE11 doesn't support `type="time"`

https://codepen.io/anon/pen/ppYEOz?editors=1010
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

**Comment by KaelWD** [comment]
This is a problem with vuetify
