### ISSUE TITLE
Font Awesome is not working using <v-icon>

### ISSUE THREAD

**Issue by kaisumli** [vuetifyjs/vuetifyjs.com#245]
I am following the documentation using <v-icon>fa-lock</v-icon> for font-awesome icon, but it is not working.

The code is also failing in the code pen example linked in the vuetifyjs documentation:
https://vuetifyjs.com/components/icons
https://codepen.io/pen/?&editors=100

**Comment by johnleider** [comment]
The issue board is strictly for bugs. Please direct all questions to the official [Discord](https://chat.vuetifyjs.com) server.
