### ISSUE TITLE
Why vuetifyjs.com does not use Nuxt.js?

### ISSUE THREAD

**Issue by dojineko** [vuetifyjs/vuetifyjs.com#264]
hello,
im translating Vuetify.js documents to japanese.

Nuxt.js is a better way to SSR / Static Site Generator with Vue.js.
i think that it is perfect for vuetifyjs.com.

if you could change it to use Nuxt.js, i am happy because it makes working easier.
if there is a reason not to do, i would like to know.

thanks :)

**Comment by johnleider** [comment]
It doesn't support nuxt because when it was being built, nuxt did not support locally linked packages and was unusable. Thank you for the suggestion, but after 6 months of work into this, definitely not flipping a switch to change.

**Comment by dojineko** [comment]
oh, i understood  😇

**Comment by nekosaur** [comment]
Also, what exactly is making the translation work harder that would be easier if using nuxt?

**Comment by dojineko** [comment]
although i started working on the server for development and checking the layout, i worked on translation, but it seemed that the screen update was slightly slower than when using Nuxt.js. 
however, it seems that Webpack and Hot-Loading are using in currently, so it may be just my imagination. 🤔
