### ISSUE TITLE
1.0.0 expansion-panel  cant find

### ISSUE THREAD

**Issue by chenfangyi931** [vuetifyjs/vuetifyjs.com#277]
![qq 20180214110955](https://user-images.githubusercontent.com/22320648/36186082-a4f208e8-1177-11e8-9bc3-ee4f08645f4c.png)

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.
