### ISSUE TITLE
Navigation-drawer always open initially

### ISSUE THREAD

**Issue by jrvaja** [vuetifyjs/vuetifyjs.com#288]
Hey Team,

I have just encountered this issue.

Navigation drawer always open in tab/mobile screen for such layouts:

**Regeneration Link:**
https://vuetifyjs.com/en/examples/layouts/complex

Steps:
* Open the link in the browser
* Now resize upto tab/mobile screen. Here, sidebar will be hidden automatically.
* Now. refresh page
OR
Load this link in tablet/ipad/mobile.

We need to close navigation drawer first in this case all time.

**Comment by KaelWD** [comment]
c2c0a99eab5f3b8c161167ae368065c1766be878
