### ISSUE TITLE
touch support -> ssr link is invalid

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetifyjs.com#316]
https://vuetifyjs.com/en/directives/touch-support

![image](https://user-images.githubusercontent.com/16421948/36631835-a6c65b52-19d2-11e8-8eaf-c5b9a4968651.png)

Links to https://vuetifyjs.com/en/guides/ssr instead of https://vuetifyjs.com/en/guides/server-side-rendering

Possibly related, the links on the SSR and a-la-carte pages are also incorrect: 
![image](https://user-images.githubusercontent.com/16421948/36631846-cc2c6076-19d2-11e8-8ec3-f701ce5f2992.png)

**Comment by jacekkarczmarczyk** [comment]
fixed on dev
