### ISSUE TITLE
Contributing guide doesn't load when visited directly

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetifyjs.com#317]
https://vuetifyjs.com/en/getting-started/contributing

![image](https://user-images.githubusercontent.com/16421948/36631932-bf77b56e-19d3-11e8-9d56-789a5c8b2e5b.png)

**Comment by bdeo** [comment]
I'm unable to repro this on current dev.

**Comment by johnleider** [comment]
Only seems to be happening on production. Even building locally and starting the app doesn't produce this.

**Comment by KaelWD** [comment]
Maybe cloudflare's messing with it somehow.

**Comment by jacekkarczmarczyk** [comment]
Looks fixed (1.0 and 1.1)
