### ISSUE TITLE
[a-la-carte] Importing components on .vue file level without transform-imports not work in every case

### ISSUE THREAD

**Issue by Igloczek** [vuetifyjs/vuetifyjs.com#324]
Not every component by default exports actually a component or the object containing other components, so there is no way to always be able to use the spread operator `...`.

I dig through the code and there is a list of the components that contain others inside of them:
```
VBreadcrumbs
VCard
VCarousel
VDataTable
VDatePicker
VExpansionPanel
VGrid
VList
VRadioGroup
VStepper
VTabs
VTimePicker
VToolbar
```

If your app needs some of the components listed above, you can't import them via `import { VGrid } from 'vuetify'`, b/c this way the output is possible to use only with `Vue.use()`, b/c default export of this components is an installer.

If you really want to get the real components, you need to ignore recommendations about using `transform-imports` and go with `import * as VGrid from 'vuetify/es5/components/VGrid'` and then using spread operator add it to the `components` object.

This leads (me) to the question if recommending the `transform-imports` for everyone is a really good thing.

**Comment by KaelWD** [comment]
Exports were changed to be spreadable with transform-imports, and this was noted in the documentation. In 1.3 you import individual components from `'vuetify/lib'`, there are no longer bundles.
