### ISSUE TITLE
[Feature Request] There are 5 languages

### ISSUE THREAD

**Issue by Dob6458** [vuetifyjs/vuetifyjs.com#355]
### Problem to solve
On the Vuetify website, there are 5 languages.

### Proposed solution
The solution is to add a 6th language (French).

**Comment by nekosaur** [comment]
All of our translation efforts are community driven. If you are interested in starting a french translation, please read [this](https://github.com/vuetifyjs/vuetifyjs.com#want-to-help-with-the-translation) and come join us at https://chat.vuetifyjs.com.
