### ISSUE TITLE
undocumented v-btn-toggle

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetifyjs.com#357]
There are few examples on buttons page (https://vuetifyjs.com/en/components/buttons#example-toggle) but API is not documented. It deserves its own page imho

![image](https://user-images.githubusercontent.com/15625235/37552280-828535ca-29e4-11e8-8382-3e23451a84b6.png)

**Comment by johnleider** [comment]
This can be an effort once we update v-btn to MD2

**Comment by jacekkarczmarczyk** [comment]
fixed on dev
