### ISSUE TITLE
[Bug Report] Documentation for version 0.14 is unavailable

### ISSUE THREAD

**Issue by JILeXanDR** [vuetifyjs/vuetifyjs.com#361]
### Versions and Environment
**Vuetify:** 0.14.0
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.146
**OS:** Linux x86_64

### Steps to reproduce
Go link https://vuetifyjs.com/releases/0.14

### Expected Behavior
Documentation is available

### Actual Behavior
Documentation is unavailable

**Comment by jacekkarczmarczyk** [comment]
Docs from Precambrian era has been removed from the site, but you can still clone https://github.com/vuetifyjs/docs repo and build it by yourself (`yarn && yarn run dev`)
