### ISSUE TITLE
Invalid props shown for v-flex

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetifyjs.com#367]
Most of these will only work on v-layout:
![image](https://user-images.githubusercontent.com/16421948/37777544-ef4b7aec-2e3b-11e8-9901-a58749a4736f.png)

**Comment by BennyAlex** [comment]
@KaelWD 
Please also add self-align properties to v-flex

**Comment by chanlito** [comment]
any progress on this?

**Comment by ScreamZ** [comment]
@johnleider Hello dude, I think this is important
