### ISSUE TITLE
 Unknown custom element: <v-data-iterator>

### ISSUE THREAD

**Issue by Manghao** [vuetifyjs/vuetifyjs.com#370]
Hello,
I want used v-data-iterator, but I've an error : 

> Unknown custom element: <v-data-iterator> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

I took the example to try this component but it does not work.

**Comment by nekosaur** [comment]
Please only create issues with the provided [issue creator](https://issues.vuetifyjs.com). Additionally, you've created this issue in the wrong repository. This repo is for the documentation.

You can join us at https://chat.vuetifyjs.com if you have questions or need help.
