### ISSUE TITLE
[Feature Request] There is no link for Issue Creator

### ISSUE THREAD

**Issue by JesusCrow** [vuetifyjs/vuetifyjs.com#383]
### Problem to solve
I couldn't find a link to https://issues.vuetifyjs.com/ anywhere in docs.

### Proposed solution
Add a link to these possible locations:
- Navigation drawer
- https://vuetifyjs.com/en/getting-started/contributing
- https://vuetifyjs.com/en/getting-started/frequently-asked-questions

**Comment by KaelWD** [comment]
![image](https://user-images.githubusercontent.com/16421948/38041862-97e296e2-32fe-11e8-9324-92c25c4658c4.png)

**Comment by JesusCrow** [comment]
Yes... Probably the only place I didn't click :D Sorry

But still, would be nice if algolia search would show it as suggestion. (Currently it doesn't, is it because it's under different subdomain?)

It might be useful to add it here:
![image](https://user-images.githubusercontent.com/6717694/38077427-9acbddf8-3341-11e8-9557-4da571a63e57.png)
