### ISSUE TITLE
[Bug Report] No message about no data in select list with asynchronous items

### ISSUE THREAD

**Issue by Detr8** [vuetifyjs/vuetifyjs.com#386]
### Versions and Environment
**Vuetify:** 1.0.11
**Vue:** 2.5.16
**Browsers:** Chrome 64.0.3282.186
**OS:** Windows 10

### Steps to reproduce
In the demo https://vuetifyjs.com/en/components/selects#example-asynchronous enter "123" text

### Expected Behavior
Control shows "No data" message or slot.

### Actual Behavior
Nothing. 
If first I enter text that exists in the states then control shows list with finded items. Then I again  enter "123" text and control show "No data message"

### Reproduction Link
[ https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/selects/asynchronous.vue ]( https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/selects/asynchronous.vue )

**Comment by jacekkarczmarczyk** [comment]
seems to be fixed in 1.1 branch
https://next.vuetifyjs.com/en/components/selects#example-asynchronous
