### ISSUE TITLE
Button aligment issue

### ISSUE THREAD

**Issue by 7iomka** [vuetifyjs/vuetifyjs.com#392]
.btn__content has property height: inherit, and this breaks vertical aligment of icon inside a button in official demo site.

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
