### ISSUE TITLE
[Bug Report] Codepen for goTo motion scrolling is broken

### ISSUE THREAD

**Issue by WuerfelDev** [vuetifyjs/vuetifyjs.com#422]
### Versions and Environment
**Vuetify:** 1.0.14
**Vue:** 2.5.16
**Browsers:** Vivaldi 1.95.1077.60, Mozilla Firefox
**OS:** Linux x86_64, Linux

### Steps to reproduce
https://vuetifyjs.com/en/motion/scrolling
clicking "edit in codepen"

### Expected Behavior
It's expected to work like on the vuetify.com page

### Actual Behavior
pen has no functionality

### Reproduction Link
[https://codepen.io/anon/pen/eMqbeg](https://codepen.io/anon/pen/eMqbeg)

### Other comments
seems like - at least - the v-if doesn't work there

**Comment by KaelWD** [comment]
Fixed by 5516329548a80519b16499fda2bb8ab85f6082c8
