### ISSUE TITLE
V-tabs component doesn't work

### ISSUE THREAD

**Issue by Lunberg88** [vuetifyjs/vuetifyjs.com#428]
Hi, have an issue with this component...

template: `
<template>
  <v-tabs fixed centered>

    <v-tabs-bar class="cyan" dark>

      <v-tabs-slider class="yellow"></v-tabs-slider>

      <v-tabs-item
        v-for="i in items"
        :key="i"
        :href="'#tab-' + i"
      >

        {{ i }}

      </v-tabs-item>

    </v-tabs-bar>

    <v-tabs-items>

      <v-tabs-content
        v-for="i in items"
        :key="i"
        :id="'tab-' + i"
      >

        <v-card flat>

          <v-card-text>{{ text }}</v-card-text>

        </v-card>

      </v-tabs-content>

    </v-tabs-items>
  </v-tabs>

</template>
`

There are few errors:
`
[Vue warn]: Unknown custom element: <v-tabs-content> - did you register the component correctly?

[Vue warn]: Unknown custom element: <v-tabs-item> - did you register the component correctly?

[Vue warn]: Unknown custom element: <v-tabs-bar> - did you register the component correctly?
`

**Comment by KaelWD** [comment]
Well *did* you register the component correctly?

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
