### ISSUE TITLE
v-card-media background

### ISSUE THREAD

**Issue by bhritch** [vuetifyjs/vuetifyjs.com#431]
is there any chance I could add some style to v-card-media in .card__media__background ?
like for ex., I would like to add opacity to the image? thanks

**Comment by KaelWD** [comment]
Yes. Use CSS. 

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
