### ISSUE TITLE
[Bug Report] A-La-Carte bug with 'copy components' button copying duplicates

### ISSUE THREAD

**Issue by dennington-bear** [vuetifyjs/vuetifyjs.com#443]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 65.0.3325.181
**OS:** Mac OS 10.13.4

### Steps to reproduce
https://vuetifyjs.com/en/guides/a-la-carte
In the table select show all rows
Use the selector to select all elements
then use the copy components button

### Expected Behavior
The output copied to the clipboard will contain a list of unique components no duplicates

### Actual Behavior
The output copied to the clipboard is perfect just the list contains duplicates like four VLists etc etc.

### Reproduction Link
[https://jsfiddle.net/1cxr0y29/](https://jsfiddle.net/1cxr0y29/)

### Other comments
Its an edge case as a-la-carte users will pick and choose what to use and probably will never copy all components but I just think if someone did this they should be returned a unique list as the copy to clipboard functionality is meant to give you the ability to just paste afterwards

**Comment by jacekkarczmarczyk** [comment]
6d4f4e4ebc3175f538e5f5edc64ae035f813a1f4
