### ISSUE TITLE
[Bug Report] minifyTheme documentation is incorrect

### ISSUE THREAD

**Issue by Anima-t3d** [vuetifyjs/vuetifyjs.com#444]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.17-beta.0
**Browsers:** Chrome 66.0.3359.117
**OS:** Mac OS 10.13.4

### Steps to reproduce
Follow the description as stated on: https://github.com/vuetifyjs/vuetifyjs.com/blob/dev/pages/style/ThemePage.vue#L72-L76

### Expected Behavior
It to minify the page

### Actual Behavior
Prevents the css from loading properly

### Reproduction Link
[https://jsfiddle.net/u7ry3x7p/](https://jsfiddle.net/u7ry3x7p/)

### Other comments
Fix is to add `css` in arguments and replace `val` and `null` with css:

Change:
```
minifyTheme: function () {
      return process.env.NODE_ENV === 'production'
        ? val.replace(/[\s|\r\n|\r|\n]/g, '')
        : null
    }
```
To:
```
		minifyTheme: function (css) {
			return process.env.NODE_ENV === 'production'
				? css.replace(/[\s|\r\n|\r|\n]/g, '')
				: css
		}
```

**Comment by jacekkarczmarczyk** [comment]
5cfae29d2a19e70f49e5aa19be6fdcbaae464701
