### ISSUE TITLE
How to: dblclick, longpress, or double tap on v-list-tile

### ISSUE THREAD

**Issue by saknarak** [vuetifyjs/vuetifyjs.com#445]
1. How to add event @dblclik, @longpress, @tap, or @doubleTap
on v-list-tile component

2. It would be nice to be a link, without having @click, href, and to attribute.
May be have new property link: Boolean or something else

```
isLink () {
      return this.href || this.to ||
        (this.$listeners && (this.$listeners.click || this.$listeners['!click']))
    }
```

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for documentation-specific bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

Please only create issues with the provided [issue creator](https://issues.vuetifyjs.com).
