### ISSUE TITLE
Document global icon config

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetifyjs.com#454]
vuetifyjs/vuetify#3591

**Comment by appurist** [comment]
I probably owe this to the project too, so I'll volunteer to fill in whatever is missing as soon as I can (hopefully in the next couple of days).  And noting Kael provided the link to the defs [here](https://github.com/vuetifyjs/vuetify/blob/dev/index.d.ts#L19-L33) for nice reference too. And the predefined sets [here](https://github.com/vuetifyjs/vuetify/blob/dev/src/components/Vuetify/mixins/icons.js).

**Comment by jacekkarczmarczyk** [comment]
Fixed by https://github.com/vuetifyjs/vuetifyjs.com/commit/44bce37b9fd0c92d0c570635ea9ae00fcda9addf
