### ISSUE TITLE
[Feature Request] Option to allow v-data-table select-all checkbox to only select filtered visible rows

### ISSUE THREAD

**Issue by ahtti** [vuetifyjs/vuetifyjs.com#455]
### Problem to solve
If select-all checkbox is enabled, the behaviour of the select all ignored and filtering done on the table data. It will set even filtered our rows as selected.

### Proposed solution
Proposed to add an attribute that will modify the behaviour of of select all to only select filtered/visible rows

**Comment by nekosaur** [comment]
This repository is for the vuetifyjs documentation. Please create a new issue on the vuetifyjs repository.
