### ISSUE TITLE
Why router/component transition not documented?

### ISSUE THREAD

**Issue by canyoudev** [vuetifyjs/vuetifyjs.com#456]
I found out that I can use `<v-slide-y-transition>`

There's not a single word about this option in Docs. 

Why? Where I can find all transition Documentation?

**Comment by jacekkarczmarczyk** [comment]
It is documented here: https://vuetifyjs.com/en/motion/transitions

**Comment by canyoudev** [comment]
@jacekkarczmarczyk are you stupid or just want to look like stupid? Please point me where at least a fucking word about `<v-slide-y-transition>`. Yeah, I thought so.

**Comment by KaelWD** [comment]
People make mistakes, no need to be a cunt about it.

**Comment by jacekkarczmarczyk** [comment]
Maybe I am, but it doesn't change the fact, that it's mentioned in docs
![image](https://user-images.githubusercontent.com/15625235/39904365-a4703c96-5501-11e8-95e1-92ebaa8a79dd.png)
![image](https://user-images.githubusercontent.com/15625235/39904383-ba11ec0c-5501-11e8-97ba-b2ac4f141ac1.png)
