### ISSUE TITLE
[WIP] Adding documentation for v-divider vertical props

### ISSUE THREAD

**Issue by bdsoha** [vuetifyjs/vuetifyjs.com#457]
The new `vertical` property on the `v-divider` is missing documentation.

Getting to work on that now.

**Comment by KaelWD** [comment]
Make PRs from the `release/1.1` branch for now.

**Comment by nekosaur** [comment]
I've added a prop description for `vertical` but we still need a new example for it.

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/components/dividers#example-vertical
