### ISSUE TITLE
[Bug Report] Component API explorer regression

### ISSUE THREAD

**Issue by DRoet** [vuetifyjs/vuetifyjs.com#460]
### Versions and Environment
**Vuetify:** 1.1.0-alpha.2
**Vue:** 2.5.16
**Browsers:** Chrome 60.0.3112.101
**OS:** Windows 8.1

### Steps to reproduce
1) Go to https://next.vuetifyjs.com/en/components/api-explorer
2) Start typing a component name such as "v-app"

### Expected Behavior
I should be able to continue typing w/ autocomplete

### Actual Behavior
I am unable to type after the letter 'v'

### Reproduction Link
[https://github.com/vuetifyjs/vuetifyjs.com](https://github.com/vuetifyjs/vuetifyjs.com)

### Other comments
I found this while looking through the 1.1-alpha docs.

**Comment by KaelWD** [comment]
Woah, nice catch. This is actually a bug with the library though, I've created an issue on the correct repo.
