### ISSUE TITLE
[Bug Report] The v-dialog scrollable is useless under "chrome 54"

### ISSUE THREAD

**Issue by trimmeryang** [vuetifyjs/vuetifyjs.com#463]
### Versions and Environment
**Vuetify:** 1.1.0-alpha.2
**Vue:** 2.5.2
**Browsers:** Chrome 54.0.2840.100
**OS:** Linux x86_64

### Steps to reproduce
1 Click the scrollable in the "Open Dialog".
2 Can not scroll under Chrome 54

### Expected Behavior
Can scroll in the v-dialog

### Actual Behavior
Can not scroll in the v-dialog

### Reproduction Link
[https://vuetifyjs.com/en/components/dialogs#Scrollable](https://vuetifyjs.com/en/components/dialogs#Scrollable)

**Comment by KaelWD** [comment]
If this is still a problem it should be reported on the main vuetify repo. It should also be noted the "chrome support" only means the latest couple of versions, as most sensible people leave it to update automatically.
