### ISSUE TITLE
update information about "required" fields

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetifyjs.com#464]
https://next.vuetifyjs.com/en/components/text-fields#example-required-fields

_"\*indicates required field"_ and section text is not valid any longer due to removed "\*"

**Comment by KaelWD** [comment]
Can probably just remove that example completely.

**Comment by peluprvi** [comment]
Removed in https://github.com/vuetifyjs/vuetifyjs.com/pull/490

**Comment by KaelWD** [comment]
Say it there then, not here.

**Comment by jacekkarczmarczyk** [comment]
fixed by https://github.com/vuetifyjs/vuetifyjs.com/pull/490
