### ISSUE TITLE
[Bug Report] RadioGroup: When programmatically changing possible values and input value, checked Value is not displayed correctly.

### ISSUE THREAD

**Issue by M3psipax** [vuetifyjs/vuetifyjs.com#465]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Firefox 59.0, Google Chrome
**OS:** Windows 10

### Steps to reproduce
When possible values for a radio group are changed programmatically and input value is changed programmatically as well in quick succession, then the radio button corresponding to the input value is not displayed as checked and its value for 'isActive' remains false.

In the codepen, simply press the 'Switch' button to observe the behaviour.

### Expected Behavior
The RadioButton corresponding to the input value should be displayed as checked.

### Actual Behavior
The RadioButton corresponding to the input value is not displayed as checked.

### Reproduction Link
[https://codepen.io/johnjleider/pen/bgJOrX](https://codepen.io/johnjleider/pen/bgJOrX)

**Comment by jacekkarczmarczyk** [comment]
Save the codepen first
