### ISSUE TITLE
Missing invert colors at components/dialogs

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetifyjs.com#47]
![image](https://user-images.githubusercontent.com/1561360/33402152-cf9a0382-d542-11e7-95e0-6cf6b8942af7.png)

![image](https://user-images.githubusercontent.com/1561360/33402171-e2b0526e-d542-11e7-9653-a11c1903b28b.png)

![image](https://user-images.githubusercontent.com/1561360/33402200-effc8604-d542-11e7-81f0-3a6e9b567c3c.png)

**Comment by johnleider** [comment]
done on purpose.
