### ISSUE TITLE
[Bug Report] Incorrect material-design-icons-iconfont css path

### ISSUE THREAD

**Issue by lindgr3n** [vuetifyjs/vuetifyjs.com#470]
### Versions and Environment
**Vuetify:** 1.0.17
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.139
**OS:** Windows 10

### Steps to reproduce
* Go to https://vuetifyjs.com/en/getting-started/quick-start
* Copy the css path specified in code block 

```
// index.js or main.js
import 'material-design-icons-iconfont/dist/material-design-icons.min.css' // Ensure you are using css-loader
```
* Paste into your project
* Path not found

### Expected Behavior
Should find the css specified. ".min." dont exist need to use
```
import 'material-design-icons-iconfont/dist/material-design-icons.css' 
```

### Actual Behavior
Path not found error

### Reproduction Link
[https://codesandbox.io/s/523nk7o72l](https://codesandbox.io/s/523nk7o72l)

**Comment by jacekkarczmarczyk** [comment]
Already fixed https://github.com/vuetifyjs/vuetifyjs.com/issues/449
