### ISSUE TITLE
[Feature Request] [v-data-table] column headers always visible option

### ISSUE THREAD

**Issue by diskman** [vuetifyjs/vuetifyjs.com#471]
### Problem to solve
Better usability of v-data-table in case of large number of rows and columns

### Proposed solution
Add configuration property on v-data-table to make columns always visible

**Comment by nekosaur** [comment]
Duplicate of https://github.com/vuetifyjs/vuetify/issues/1547

Also issue is on the wrong repo. This is for the vuetify documentation
