### ISSUE TITLE
[Bug Report] Update examples that use rules props to avoid console errors

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetifyjs.com#472]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.170
**OS:** Windows 7

### Steps to reproduce
Open the console, type a name and clear the text field

### Expected Behavior
No console errors

### Actual Behavior
[Vue warn]: Error in nextTick: 'TypeError: Cannot read property 'length' of null'

### Reproduction Link
[https://codepen.io/anon/pen/GdYqRG?editors=1011](https://codepen.io/anon/pen/GdYqRG?editors=1011)

### Other comments
Documentation rules of `() => last.length > 0` or similar should be `() => last && last.length > 0` to avoid console errors.

**Comment by jacekkarczmarczyk** [comment]
fixed by https://github.com/vuetifyjs/vuetifyjs.com/pull/490
