### ISSUE TITLE
Text-Fields - Examples - Incorrect prop `max` in input validation example

### ISSUE THREAD

**Issue by peacefulseeker** [vuetifyjs/vuetifyjs.com#473]
https://vuetifyjs.com/en/components/text-fields#example-validation

https://github.com/vuetifyjs/vuetifyjs.com/blob/master/examples/text-fields/validation.vue#L23

Incorrect prop.
I guess should be :counter="15" instead of max="15"

**Comment by KaelWD** [comment]
Fixed by 9a6733a07a6c4662445b0fb89ac51226fe0ba13b
