### ISSUE TITLE
[Feature Request] DataTable Selectable/Not Selectable

### ISSUE THREAD

**Issue by dexterannatuchua** [vuetifyjs/vuetifyjs.com#475]
### Problem to solve
1. Rows in DataTable that are not selectable cannot be deleted by delete selected button.

### Proposed solution
1. Datatable with select-all and v-model and delete selected button.
2. Function that can set if row is selectable/not selectable.
3. Do not return to v-model the props.item value of not selectable row.

**Comment by nekosaur** [comment]
Please create a new issue using the [issue creator](https://issues.vuetifyjs.com). This repository is for the Vuetify documentation
