### ISSUE TITLE
v-radio-group row does not work with v-for

### ISSUE THREAD

**Issue by TNTLarsn** [vuetifyjs/vuetifyjs.com#486]
see codepen

https://codepen.io/TNT_Larsn/pen/wXovmw?&editors=101

any known workaround on this?

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for documentation problems. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).

**Comment by KaelWD** [comment]
also you have v-for on the group

**Comment by TNTLarsn** [comment]
Damn you‘re right 😅
My bad
