### ISSUE TITLE
Fontawesome icons showing in development mode but not showing in webpack built/dist files 

### ISSUE THREAD

**Issue by Chimba123** [vuetifyjs/vuetifyjs.com#488]
The Fontawesome icons are  being displayed in development mode after importing them locally but are not being displayed in the distribution/production project after being built by Webpack.  They are referenced in the head of the html automatically by Webpack and have a 'fonts' folder in the root directory but are not showing when the index.html file is loaded in the browser.

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for documentation problems. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
