### ISSUE TITLE
[Feature Request] Make it clear that setting the format to 'ampm' doesn't yield an AM/PM value

### ISSUE THREAD

**Issue by shravan-kaushik** [vuetifyjs/vuetifyjs.com#491]
### Problem to solve
Follow-up of https://github.com/vuetifyjs/vuetify/issues/4240

`v-time-picker` always returns a 24-hour formatted time, and the prop `format` is just for how the picker is displayed, not for how the value it yields is formatted. So, even when `format` is explicitly set to `ampm`, we don't get an AM/PM-formatted time. It's no super clear from the docs.

### Proposed solution
Make the [documentation](https://vuetifyjs.com/en/components/time-pickers#example-time-dialog-and-menu) clearer, I guess?

**Comment by jacekkarczmarczyk** [comment]
fixed by db9fdfb1deb67fdaacb4697985e0adc18ea56b4c
