### ISSUE TITLE
[Feature Request] Vuejs devtools cannot be used on the vuetifyjs.com examples :'-(

### ISSUE THREAD

**Issue by thatandyrose** [vuetifyjs/vuetifyjs.com#510]
### Problem to solve
It would allow me to use the Vue devtools to highlight and get a better idea of how components are structured in layouts. For example, would be great to have devtools enabled on say this page: https://vuetifyjs.com/en/examples/layouts/complex

### Proposed solution
To explicitly enable dev tools? See here for more info: https://github.com/vuejs/vue-devtools/issues/190#issuecomment-355953672

> I change my CDN to a non-minified version and have Vue.config.devtools = true in my js file, then it shows up.

**Comment by nekosaur** [comment]
The source code for the entire site, including all examples is available in this very repository. Additionally, on the page you linked you can click the `<>` icon to be taken directly to the markup of the page.

**Comment by thatandyrose** [comment]
hey @nekosaur thanks for the reply. Hmm I think maybe you might have misunderstood.

So, the vuejs devtools have a very cool feature, whereby you can look at the component tree structure, and as you hover over each component in the devtools, you actually see that markup get highlighted in the browser window.

This is especially useful when looking at a structure that is complex and/or new to you... which is the exact workflow when reading docs. It's usually because you're trying to learn.

The source code is of course superuseful, but you can't see how that relates directly to what's on the screen.

The codepen is very good too (thanks to whoever had that idea!) but you still can't see what relates to the page elements without digging around.

The is of course the inbuilt elements inspector in the browser dev tools, but it's not clear what markup matches to what components.

Of course, it's all doable. For example while looking at the complex layouts, to know which draw is which I edited the contents of the draw so I could easily see what is what.

So, it's fine. But if we could use the devtools it would just be that extra functionality that would make things even easier 👍 

Hope that makes sense!

**Comment by jacekkarczmarczyk** [comment]
You can clone the repo and run it locally

**Comment by johnleider** [comment]
devtools are meant for local use. Suggestion would be to copy and paste the code in your local project. As stated above, the docs are public and you can clone/run them locally and see for yourself :)

Thank you for using Vuetify.

**Comment by thatandyrose** [comment]
@johnleider no worries, makes sense 👍 thanks so much!
