### ISSUE TITLE
Documentation issue: Form Component sample email validation includes a regex with severe backtracking problems

### ISSUE THREAD

**Issue by Pointy** [vuetifyjs/vuetifyjs.com#512]
On [this page](https://vuetifyjs.com/en/components/forms) describing the "Form Component", there is sample code that includes validation for an email address field. The validation code employs a regular expression to check the syntax of the email address as it is being typed. 

There are two problems with that regular expression. The first is that it is simply inaccurate, and it will report false negatives for perfectly valid email addresses.

More serious however is the second problem, which is that the two instances of nested quantifiers cause catastrophic runaway backtracking when the input email address is long. It's possible to see the effect of that right there on the page: simply start typing a long hypothetical email address, and after a point your browser will stop responding.

Here is the regex in question:

    /^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/

The `\w+` nested inside the groups that have `*` quantifiers are (I think) what cause the problem. The regular expression could be fixed, but I think it would be helpful to people trying to use the software (and who will definitely directly copy that code, at least sometimes) to create a more real-world-useful validation script for email addresses.

**Comment by Pointy** [comment]
[Relevant Stackoverflow question](https://stackoverflow.com/questions/51084708/vuetify-email-rules-hangs-the-web-page-when-we-type-very-long-emails)

**Comment by KaelWD** [comment]
vuetifyjs/vuetify#2588
vuetifyjs/vuetify#3523

`/.+@.+/` is probably the only actual valid email regex that won't have false negatives.
