### ISSUE TITLE
[Bug Report] [v-tab-items] touch swiping ignores disabled tab items

### ISSUE THREAD

**Issue by NerijusD** [vuetifyjs/vuetifyjs.com#516]
### Versions and Environment
**Vuetify:** 1.0.18
**Vue:** 2.5.12
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
Open provided codepen on mobile, or in browser with enabled mobile functionality (touch points enabled), then try to swipe through tab-item bodies.

### Expected Behavior
Swiping with touch pointer (on mobile) throughout tab-item body should switch only to enabled tabs, if there are no enabled tabs, swiping shouldn't be permitted at all.

### Actual Behavior
Swiping with touch pointer (on mobile) throughout tab-item body works on all tabs even if some are disabled.

### Reproduction Link
[https://codepen.io/anon/pen/xzMZMv?&editors=101](https://codepen.io/anon/pen/xzMZMv?&editors=101)

### Other comments
Right now, on mobile it is possible to get into state, which wouldn't be possible on desktop due to touch swiping ignoring disabled tab items.

**Comment by johnleider** [comment]
There is no correlation as far as disabled between the two. This is another reason why we need to abstract tabs functionality into a core component.

**Comment by KaelWD** [comment]
This repository is only for documentation issues. Problems with the framework itself should be submitted to https://github.com/vuetifyjs/vuetify
