### ISSUE TITLE
[Feature Request] background-color for v-progress-circular

### ISSUE THREAD

**Issue by jagroeneveld** [vuetifyjs/vuetifyjs.com#521]
### Problem to solve
ability to determine the color of the stroke of v-progress-circular

### Proposed solution
to add a prop 'background-color' to v-progress-circular that colors the "background stroke" of the circle itself (not the background of the circle)

**Comment by KaelWD** [comment]
This repository is only for documentation issues. Feature requests should be submitted to https://github.com/vuetifyjs/vuetify
