### ISSUE TITLE
[Feature Request] Please provide the 1.0 documentation as well

### ISSUE THREAD

**Issue by jwhentsch** [vuetifyjs/vuetifyjs.com#523]
### Problem to solve
Provides the 1.0 documentation

### Proposed solution
just link it on the documentation page, like you did with the 0.x-Versions

**Comment by KaelWD** [comment]
0.x were all breaking changes, 1.1 is backwards compatible with 1.0 so we won't be archiving it. If you still need 1.0 examples for some reason they will be temporarily available at http://v1.vuetifyjs.com

**Comment by jacekkarczmarczyk** [comment]
already fixed
