### ISSUE TITLE
[Bug Report] Example uses <form> instead of <v-form>

### ISSUE THREAD

**Issue by jagroeneveld** [vuetifyjs/vuetifyjs.com#526]
### Versions and Environment
**Vuetify:** 1.1.4
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Linux x86_64

### Steps to reproduce
open vuetify.com
Search for 'form'
Look at examples for Vuelidate and vee-validate 
CodePen examples are working but "form" is used whereas the topic is "v-form"

### Expected Behavior
"v-form" is used in two last examples

### Actual Behavior
"form" is used 

### Reproduction Link
[https://codepen.io/pen/?&editors=101](https://codepen.io/pen/?&editors=101)

### Other comments
I tried to use "<" and > but those html tags don't show. How can I make <form> show?

**Comment by KaelWD** [comment]
The topic is "forms', those are examples of how to third-party validation libraries as a *replacement* for v-form.
