### ISSUE TITLE
[Bug Report] v-text-field : prefix is overrided with value

### ISSUE THREAD

**Issue by amazzoccone** [vuetifyjs/vuetifyjs.com#527]
### Versions and Environment
Vuetify: 1.1.4
Browsers: Chrome 67.0.3396.99
OS: macOS High Sierra

### Steps to reproduce
Create a v-text-field with a large prefix
```
<v-text-field
    label="Amount"
    value="10.00"
    prefix="USD$"
  ></v-text-field>
```

### Expected Behavior
Prefix text should not be overrided with value.

### Actual Behavior
Values overrided

### Reproduction Link
https://codepen.io/anon/pen/KBwGJP

**Comment by jacekkarczmarczyk** [comment]
Wrong repo and also duplicate of https://github.com/vuetifyjs/vuetify/issues/3485
