### ISSUE TITLE
[Bug Report] Auto complete or select doesn't open menu list automatically on focus

### ISSUE THREAD

**Issue by BharathAj** [vuetifyjs/vuetifyjs.com#537]
### Versions and Environment
**Vuetify:** 1.1.4
**Last working version:** 1.0.19
**Vue:** 2.5.2
**Browsers:** Safari 11.1.1
**OS:** Mac OS 10.13.5

### Steps to reproduce
Refer the link https://codepen.io/anon/pen/gjLYaZ?editors=1010
Issue 1.  Set autofocus property to v-select or v-autocomplete menu list is not open automatically [in v1.0.19 it's working]
Issue 2. manually Set focus to these components also not triggering menu list  [in v1.0.19 itself not working ]

### Expected Behavior
Activate the menu while the focus  triggered or provide a ​property  to open on focus like 'open-on-clear'

### Actual Behavior
The menu ​is not activated​ automatically on focus 

### Reproduction Link
[https://codepen.io/anon/pen/gjLYaZ?editors=1010](https://codepen.io/anon/pen/gjLYaZ?editors=1010)

### Other comments
I'm not sure whether this is a bug or intentional 
I have added the following line to resolve​ the issue for v-autocomplete
this.activateMenu()

 isFocused: function isFocused(val) {
            if (val) {
                this.$refs.input && this.$refs.input.select();
               <p style="color:red"> this.activateMenu()</p> 
            } else {
                this.updateSelf();
            }
        },

**Comment by jacekkarczmarczyk** [comment]
This should be reported in the main repo
