### ISSUE TITLE
[Bug Report] Clicking on a sliders tick doesn't work

### ISSUE THREAD

**Issue by jwhentsch** [vuetifyjs/vuetifyjs.com#550]
### Versions and Environment
**Vuetify:** 1.1.8
**Vue:** 2.5.16
**Browsers:** Safari 11.1.2, Google Chrome, Mozilla Firefox, Safari
**OS:** Mac OS 10.13.6

### Steps to reproduce
just try to click directly on the tick. If the ticks are bigger, it's even worse.

### Expected Behavior
should go through the ticks

### Actual Behavior
it's not working

### Reproduction Link
[https://codepen.io/pen/?&editors=101](https://codepen.io/pen/?&editors=101)

**Comment by KaelWD** [comment]
This is for documentation-specific issues only, and you forgot to save then codepen. 

Possible duplicate of vuetifyjs/vuetify#4464

**Comment by alan1111** [comment]
I have the same problem, only click track (except ticks) is fine.

**Comment by alan1111** [comment]
@jwhentsch,I have the same problem, only click track (except ticks) is fine.
https://next.vuetifyjs.com/en/components/sliders#introduction
You can click tick directly, it not works fine
