### ISSUE TITLE
[Feature Request] Can you please provide a 3-way-switch

### ISSUE THREAD

**Issue by jwhentsch** [vuetifyjs/vuetifyjs.com#551]
### Problem to solve
Using this switch In filters I could switch between: active | either | inactive
The switch should look like the normal v-switch but with a middle position. And it should be possible to configure the values for each position.

### Proposed solution
Implement a <v-3switch> as an enhancement of <v-switch>. I've looked into the code for VSwitch to do i myself, actually I don't understand the code for VSwitch with all it's mixins and the stylus-stuff at all. Someone with a deep understanding of that all could possibly implement this in a relative short time.
In the mean time I try to implement my own solution with a slider with ticks and tick labels - but this doesn't look as nice as an expanded VSwitch. Am I the only one who needs that element?

**Comment by KaelWD** [comment]
This repo is for documentation-specific issues only.
