### ISSUE TITLE
[Bug Report] Text Field requires input value when default is 0

### ISSUE THREAD

**Issue by phudangthe** [vuetifyjs/vuetifyjs.com#554]
### Versions and Environment
**Vuetify:** 1.1.8
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.99
**OS:** Windows 10

### Steps to reproduce
1. Input value for field Name
2. Click on Submit button

### Expected Behavior
Alert "Ok"

### Actual Behavior
Form invalid: "Amount is required", although Amount field's value is 0

### Reproduction Link
[https://codepen.io/phudangthe/pen/BPmqdo?editors=1010](https://codepen.io/phudangthe/pen/BPmqdo?editors=1010)

### Other comments
Field Amount always invalid when default value is 0, if we enter value 0 then it works well

**Comment by KaelWD** [comment]
Welcome to javascript
![image](https://user-images.githubusercontent.com/16421948/43367792-15cb9110-9396-11e8-8886-c7d5bcd717b4.png)
