### ISSUE TITLE
Missing Translations for Textarea flat and solo API

### ISSUE THREAD

**Issue by BenRichter** [vuetifyjs/vuetifyjs.com#557]
The translation for flat and solo are missing in https://vuetifyjs.com/en/components/textarea#api

```
flat
Mixins.Soloable.props.flat
```

I tried to solve it myself, but the keys seem to be correct. Maybe the _Soloable_-Mixin isn't registered right, but there was no difference compared to e. g. _Validatable_ which is resolved correctly.

**Comment by jacekkarczmarczyk** [comment]
fixed on dev
