### ISSUE TITLE
text-fields textarea and box style examples can be updated to use invert color button

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetifyjs.com#56]
![image](https://user-images.githubusercontent.com/1561360/33403140-4e0f0da4-d546-11e7-9814-0ddae625739a.png)

![image](https://user-images.githubusercontent.com/1561360/33403155-5deb4f76-d546-11e7-8998-8e947c71ab31.png)

**Comment by zaken** [comment]
Fixed Box style example. Textarea one is a design decision I think. @johnleider should say.
