### ISSUE TITLE
[Feature Request] goTo does not work with custom scrollbar

### ISSUE THREAD

**Issue by jrvaja** [vuetifyjs/vuetifyjs.com#592]
### Problem to solve
goTo does not work with custom scrollbar

### Proposed solution
It would be great if vuetify built-in comes with custom scrollbars. Custom scroll is normal now days for all web site and application for pleasant ui.
I am using PerfectScrollbar.

**Comment by jacekkarczmarczyk** [comment]
Please provide reproduction

**Comment by jrvaja** [comment]
@jacekkarczmarczyk It seems, I could not provide you regeneration from JsFiddle or codepan.
Shall I share you a public repository over the github?

**Comment by jacekkarczmarczyk** [comment]
It's ok as long as it contains **minimal** code required to reproduce a problem

**Comment by jrvaja** [comment]
Hey @jacekkarczmarczyk ,

Please check this repo:
https://github.com/jrvaja/vuetify-goto

**Comment by jacekkarczmarczyk** [comment]
First of all:
![image](https://user-images.githubusercontent.com/15625235/45022853-88391e00-b035-11e8-808d-01f1e3371a94.png)

Second (however I haven't run this repo yet) - goTo now scrolls only the window, and you're applying the directive to some DOM element inside the content, looks like you're waiting for https://github.com/vuetifyjs/vuetify/pull/4333

**Comment by jrvaja** [comment]
@jacekkarczmarczyk 
Oh. I am sorry for inconvenience caused to you.
I just created a ticker from Document website. I will make sure this won't happen next time.

Thanks for #4333
