### ISSUE TITLE
Unable to render the data

### ISSUE THREAD

**Issue by Nasrumink** [vuetifyjs/vuetifyjs.com#614]
I am using Laravel 5.6 and Laravel Nova on my windows machine. I want to display the Vue table in my Laravel Nova custom component.

https://vuetifyjs.com/en/components/data-tables#usage--1
I have used the same example shown in the above link.
I have added the exact same code.

After page refresh nothing shows up on the screen but when i do inspect element I get the following code. 

<v-data-table 
headers="[object Object],[object Object]" // I think problem is here
items="[object Object],[object Object]" // I think problem is here
hide-actions="" class="elevation-1">
</v-data-table>

I am not able to fix the problem.

Below is my code...
` <v-data-table
    :headers="headers"
    :items="desserts"
    hide-actions
    class="elevation-1"
  >
    <template slot="items" slot-scope="props">
      <td>{{ props.item.name }}</td>
      <td class="text-xs-right">{{ props.item.calories }}</td>
      <td class="text-xs-right">{{ props.item.fat }}</td>
      <td class="text-xs-right">{{ props.item.carbs }}</td>
      <td class="text-xs-right">{{ props.item.protein }}</td>
      <td class="text-xs-right">{{ props.item.iron }}</td>
    </template>
  </v-data-table>`

`<script>
import Vue from 'vue'
import Vuetify from 'vuetify'
//Vue.use(Vuetify)
import 'vuetify/dist/vuetify.min.css' 

import axios from 'axios'

    export default {
        data () {
            return {
                headers: [
                    {
                        text: 'Dessert (100g serving)',
                        align: 'left',
                        sortable: false,
                        value: 'name'
                    },
                    { text: 'Calories', value: 'calories' },
                    { text: 'Fat (g)', value: 'fat' },
                    { text: 'Carbs (g)', value: 'carbs' },
                    { text: 'Protein (g)', value: 'protein' },
                    { text: 'Iron (%)', value: 'iron' }
                ],
                desserts: [
                    {
                        value: false,
                        name: 'Frozen Yogurt',
                        calories: 159,
                        fat: 6.0,
                        carbs: 24,
                        protein: 4.0,
                        iron: '1%'
                    },
                    {
                        value: false,
                        name: 'Ice cream sandwich',
                        calories: 237,
                        fat: 9.0,
                        carbs: 37,
                        protein: 4.3,
                        iron: '1%'
                    },
                ],
                userBlocks: {},
            }
        }, 
        components: { Vuetify },
        created () {
            axios.get('/list-wallet-requests')
                .then(response => {
                this.userBlocks = response.data
            })
            .catch(err => {
                console.log(err)
            })
        },
    }
</script>
`

**Comment by jacekkarczmarczyk** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
