### ISSUE TITLE
Could you help me why my word size is so small?

### ISSUE THREAD

**Issue by printfcoder** [vuetifyjs/vuetifyjs.com#625]
Demo on your site:

![image](https://user-images.githubusercontent.com/20906540/46876555-332ccb00-ce71-11e8-9e38-3a8babd82d0d.png)

this is I I tried, same code there were:

![image](https://user-images.githubusercontent.com/20906540/46876680-8737af80-ce71-11e8-87fe-32aad752d38a.png)

words' size are so strange
So please tell me What did I miss.

**Comment by jacekkarczmarczyk** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
