### ISSUE TITLE
Treeview does not reset when emptying tree[ ] value

### ISSUE THREAD

**Issue by rickgn** [vuetifyjs/vuetifyjs.com#626]
Based on example https://vuetifyjs.com/en/components/treeview#examples
Seems to be a lot of potential here but there are some issues.

The reset button in the hotspot demo does not work either on the website or in local environment.  

I tried in local environment multiple ways of clearing the selections such as tree = [ ], 
this.tree.splice(0,this.tree.length);

When the tree (selected values array)  is empty the checked items do not clear.  It seems to be a reactive watch issue on the value[ ] array?  

If not, there should be a method to unselect a node. I don't see anything in the documentation. 

```
<v-treeview
            v-model="treemodel"
            :load-children="fetch"
            :items="items"
            activatable
            active-class="grey lighten-4 indigo--text"
            selected-color="indigo"
            open-on-click
            selectable
            expand-icon="fas fa-caret-down"
            on-icon="fas fa-check-circle"
            off-icon="fal fa-circle"
            indeterminate-icon="fas fa-minus-circle"
            @change="onTreeChange"
          >
          </v-treeview>

     <v-btn  @click="treemodel = []" >Reset</v-btn>
```
Reset button does not do anything (copied from your example)

```
// from script
data(){
      return {
        breweries: [],
        isLoading: false,
        treemodel: [],
        types: []
      }
    },
 methods: {
      onTreeChange(e){
        console.log("TREE CHANGE", e);  // seems to emit a nice event but *is not documented*
      },
      clearSelections(){
        console.log('should clear');
        this.treemodel.splice(0,this.treemodel.length);  // should be bound to same as v-bind and reactive?
        console.log('treemodel=', this.treemodel)
    // results: treemodel is empty array but selections remain. 
      },
      removeSelection(e){
        const idx = this.treemodel.findIndex(k => k==e);
        console.log('should remove:', e, '@', idx);
        this.treemodel.splice(idx, 1);
      }
}
```

**Comment by nekosaur** [comment]
This repository is for the documentation. Please create a new issue in the vuetify repo using the [issue creator](https://issues.vuetifyjs.com). Thank you.
