### ISSUE TITLE
[Bug Report] VTabItem - 'id' is deprecated, use 'value' instead

### ISSUE THREAD

**Issue by jrvaja** [vuetifyjs/vuetifyjs.com#629]
### Versions and Environment
**Vuetify:** 1.3.0
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Mac OS 10.13.6

### Steps to reproduce
It could clearly visible on the the documentation website. So I am posting this on vuetifyjs.com issue list.
https://www.dropbox.com/s/7nfiidraknjvvnz/Screenshot%202018-10-18%2015.34.27.png?dl=0

### Expected Behavior
Please fix this warning.

### Actual Behavior
This is just a warning. But it should not be there.

### Reproduction Link
[https://codepen.io/pen/?&editors=101](https://codepen.io/pen/?&editors=101)

**Comment by jacekkarczmarczyk** [comment]
Fixed on dev https://next.vuetifyjs.com
