### ISSUE TITLE
[Feature Request] Tooltip in SpeedDial FAB

### ISSUE THREAD

**Issue by james04gr** [vuetifyjs/vuetifyjs.com#631]
### Problem to solve
Add tooltip to Fab speed-dial and to its menu buttons. With that the user could be easily informed about the actions provided from the menus. 

### Proposed solution
Maybe Wrap the buttons with the v-tooltip tag or add an attribute called tooltip with the label on it..!

**Comment by jacekkarczmarczyk** [comment]
1. This repo is only for documentation issues
2. Nothing stops you from wrapping fab button with `v-tooltip`
3. If it doesn't work as expected please create a bug report AND provide codepen reproduction
4. See https://github.com/vuetifyjs/vuetify/issues/3107
