### ISSUE TITLE
[Feature Request] v-select - apollo query does not reload when some item selected

### ISSUE THREAD

**Issue by NecVo** [vuetifyjs/vuetifyjs.com#651]
### Problem to solve
I have trouble with trying to invoke apollo reload query. When I got new select frame on user window, apollo is invoked if I open input list from select. That is right and it hapens again right if I click out of select frame and click on select list again.

Issue:
If I have chosen one of listed option (or selected more than one) and click out of select frame and then click into it (select list) again - apollo does not reload. That is trouble for me, because I have other components which can confluence dynamically list of items which are listed in select (e.g. list of items in database, but when I add new item 'ABC' into DB and then after click into select frame where some other option is choosen - apollo not reload and I can not see this new item 'ABC' in select list).

Does someone know how to implement that? I can not find any helpfull atribute from Vuetify man pages or I can not invoke apollo manually ( reload() ), cause I do not know in which trigger action I could do that.

I will be glad for any answer, thank you.

### Proposed solution
I would expect to be able invoke apollo automatically although I have choosen one or more  of select item.

**Comment by KaelWD** [comment]
1. This is not a documentation issue
2. Your previous issue https://github.com/vuetifyjs/vuetify/issues/5423 was already closed for being too vague
3. This most likely has nothing to do with vuetify at all, and nobody can help you if you don't provide some **runnable** code. 
4. As jacek said, github is not a support forum. Use stackoverflow, reddit, or discord with a simple reproduction of your problem.
