### ISSUE TITLE
"w/" in jumbotron example title should be "with" like in other areas

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetifyjs.com#66]
![image](https://user-images.githubusercontent.com/1561360/33455038-f5d72a10-d601-11e7-9cba-f1491f0f9966.png)

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetifyjs.com/commit/633f325475a4f70db68051cf7570cb89a74c6b1c
