### ISSUE TITLE
[Feature Request] Multiple event indicators

### ISSUE THREAD

**Issue by bobemmen** [vuetifyjs/vuetifyjs.com#666]
### Problem to solve
With v-calendar it is possible to render multiple 'event-indicators' [link to example](https://raw.githubusercontent.com/nathanreyes/v-calendar-docs/master/gitbook/images/README/welcome-1.png)

Would like to see this option in Vuetify as well!

With Vuetify 'one' event indicator is possible (example), but I don't know how to manage to make it two or even three. Is there any solution for this?

### Proposed solution
Add possibility to add multiple indicators

**Comment by KaelWD** [comment]
You've submitted an issue to the incorrect repository. Please re-create your issue [here](https://github.com/vuetifyjs/vuetify)

Thank you for your contribution and interest in improving Vuetify.
