### ISSUE TITLE
[Feature Request] Doc - Add Icon slots for Text fields in API documentation

### ISSUE THREAD

**Issue by ThomasKientz** [vuetifyjs/vuetifyjs.com#674]
### Problem to solve
The slot "Icon" is missing in the slot's API of the textfield :
https://vuetifyjs.com/en/components/text-fields#api

https://vuetifyjs.com/en/components/text-fields#example-icon-slots

### Proposed solution
Document the "icon" slot in the slot API of the textfield.

**Comment by jacekkarczmarczyk** [comment]
Duplicate of https://github.com/vuetifyjs/vuetifyjs.com/issues/576
