### ISSUE TITLE
[Duplicated] Stepper step property on v-stepper-step issue

### ISSUE THREAD

**Issue by asimkhan0** [vuetifyjs/vuetifyjs.com#677]
### Versions and Environment
**Vuetify:** 1.2.3
**Vue:** 2.5.2
**Browsers:** Chromium 70.0.3538.110
**OS:** Linux x86_64

### Steps to reproduce
simple use stepper and use older version of vuejs

its working with latest Vue but not working with vue version 2.5.2..

### Expected Behavior
should show stepper content but its not showing.

also vuetify should allow to use image in step property as <v-stepper-step step="someIcon">

### Actual Behavior
when i use string in <v-stepper-step step="string"> , it doesn't display the content

### Reproduction Link
<a href="https://codepen.io/asim-aziz/pen/NEBOPy" target="_blank">https://codepen.io/asim-aziz/pen/NEBOPy</a>

**Comment by KaelWD** [comment]
You can close issues yourself you know.
