### ISSUE TITLE
[Feature Request]I want close the <v-edit-dialog> decide by myself when click the 'Save' button.

### ISSUE THREAD

**Issue by DeFenceD** [vuetifyjs/vuetifyjs.com#682]
In reality, I want do some thing like request promise, and wait there are finish, then close the <v-edit-dialog> or keep the <v-edit-dialog> alive.
But now, I find when I click the 'Save' button, I can't prevent <v-edit-dialog> close by any code.
Since I was offer the '@save' event, I hold decide call the method 'close()' by myself.

**Comment by jacekkarczmarczyk** [comment]
![image](https://user-images.githubusercontent.com/15625235/49570125-6454e380-f968-11e8-916d-0c5df80a7679.png)
