### ISSUE TITLE
No "tag" property description in doc for "v-slide-y-transition" component

### ISSUE THREAD

**Issue by Perlover** [vuetifyjs/vuetifyjs.com#684]
https://github.com/vuetifyjs/vuetifyjs.com/blob/18dbd0a916754b2733dd737ed80bdd548b1dd44b/src/examples/transitions/todo.vue#L58

**Comment by KaelWD** [comment]
Transition components have the same API as vue's `<transition>`, or `<transition-group>` if the `group` prop is used. 

If you'd read the issue template you'd also know that this is the wrong place to be opening new issues.

**Comment by Perlover** [comment]
Now i know. But where is in the doc?

![](https://uc85bad8a67a448207e4b0acf6b9.dl.dropboxusercontent.com/cd/0/inline/AW-TrYAzguiCxlF5UutnxtCJASDyPIRTPgj84k3N3J5Hk-2ySJS1MnS9AWWUyn4Ond2b6T13AMFZD4QNZt-n7_vZPP3HnMV_L4iV7Hk1Wk4nzkUPBEc0pu0HY1d_jvOARdxhv2smNhAIaECagBtKAQf_a7HQb9AnMdQjEQXU9-wo8FYteRk112x0eWOqu-fsRKI/file)

**Comment by KaelWD** [comment]
Documentation has been rebuilt for 1.4 https://next.vuetifyjs.com/en/motion/transitions
