### ISSUE TITLE
Date and Time Pickers dark theme examples should not have invert-colors action

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetifyjs.com#72]
![image](https://user-images.githubusercontent.com/1561360/33456851-ced14b34-d607-11e7-852f-07e91e622355.png)

![image](https://user-images.githubusercontent.com/1561360/33456892-f2eb02da-d607-11e7-9ed5-2b7952272743.png)

![image](https://user-images.githubusercontent.com/1561360/33456918-055deedc-d608-11e7-8a64-e8ab094a664e.png)

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetifyjs.com/commit/d1f02b0b7586b42b1a5ad275f11a68d02792fd00
