### ISSUE TITLE
Pickers internationalization examples are overlaping each other in some resolutions

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetifyjs.com#73]
![image](https://user-images.githubusercontent.com/1561360/33457047-6402775a-d608-11e7-94f9-ec28a68f91d3.png)

![image](https://user-images.githubusercontent.com/1561360/33457030-5aca3556-d608-11e7-8a20-6ca596066047.png)

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetifyjs.com/commit/d1f02b0b7586b42b1a5ad275f11a68d02792fd00
