### ISSUE TITLE
Snackbar invert-color action should change the snackbar color, not the example content

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetifyjs.com#76]
![image](https://user-images.githubusercontent.com/1561360/33457316-40eca6e0-d609-11e7-8ab2-1f4929035f35.png)

![image](https://user-images.githubusercontent.com/1561360/33457358-5ea0336e-d609-11e7-9c81-88b505dd1f50.png)

**Comment by zaken** [comment]
Yeah, we can't do that since snackbars are not dependent on theme. There's a color example so that should suffice.
