### ISSUE TITLE
Wrong ripples examples color when dark theme

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetifyjs.com#83]
![image](https://user-images.githubusercontent.com/1561360/33457985-923e1d60-d60b-11e7-8423-edc030451dec.png)

![image](https://user-images.githubusercontent.com/1561360/33457992-9de760b8-d60b-11e7-8388-77ca33dcfba3.png)

**Comment by jacekkarczmarczyk** [comment]
Fixed with 4dbd072680d62649228d409e7931c84021e40954 (removed dark/light switch)
