### ISSUE TITLE
"w/" in directives/scrolling example title should be "with" like in other areas

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetifyjs.com#84]
![image](https://user-images.githubusercontent.com/1561360/33458059-d94b6fd2-d60b-11e7-859c-85584ed502c0.png)

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuetifyjs/vuetifyjs.com/commit/633f325475a4f70db68051cf7570cb89a74c6b1c
