### ISSUE TITLE
invalid v-toolbar-title component on /guides/server-side-rendering page

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetifyjs.com#92]
![image](https://user-images.githubusercontent.com/15625235/33470219-b12440e0-d699-11e7-9aef-117a472650e8.png)

**Comment by zaken** [comment]
What's wrong with this one?

**Comment by KaelWD** [comment]
v-toolbar-title hasn't been a thing since like 0.15

**Comment by zaken** [comment]
Docs are full of it though

**Comment by KaelWD** [comment]
Oops. I was thinking of v-toolbar-logo, which is what's in this example in the current docs. I don't know what's wrong with this one.
