### ISSUE TITLE
navdrawer z-index issue

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetifyjs.com#95]
https://next.vuetifyjs.com/components/navigation-drawers
![image](https://user-images.githubusercontent.com/15625235/33493425-9236bc72-d6f2-11e7-8a9b-414d7a01986b.png)

**Comment by peluprvi** [comment]
Duplicated https://github.com/vuetifyjs/vuetifyjs.com/issues/70
