### ISSUE TITLE
pagination has scroll bar

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuetifyjs/vuetifyjs.com#96]
https://next.vuetifyjs.com/components/paginations
![image](https://user-images.githubusercontent.com/15625235/33494642-78cb24f4-d6f6-11e7-94da-e3f2af00f2d9.png)

**Comment by zaken** [comment]
Pagination itself causing this. Most probably [this part](https://github.com/vuetifyjs/vuetify/blob/805ab5d0439b5b9bc8d66ee4b4ac860b8a307239/src/components/VPagination/VPagination.js#L97).

**Comment by johnleider** [comment]
Fixed in Vuetify.
