### ISSUE TITLE
TypeError: t.src.replace is not a function

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetifyjs.com#98]
https://next.vuetifyjs.com/components/menus

![image](https://user-images.githubusercontent.com/16421948/33494817-ab9adff6-d718-11e7-9cb2-28fd6d1bcb51.png)

Seems to be related to the markdown parser.

**Comment by johnleider** [comment]
Does this still occur?

**Comment by nekosaur** [comment]
Reopen if it still occurs
